### ISSUE TITLE
Flexible module-lecture

### ISSUE THREAD

**Issue by FraGard** [KTH-dESA/teaching_kit#10]
Ideally, we could tag the modules with themes - and a module may have multiple themes which you could browse. @lorenzo-sani  - it might be possible to add tags in the yaml meta data at the top of each slide? And then create a page which allows you to view all of the modules with a particular tag?

**Comment by FraGard** [comment]
I am not sure if we should have a demo / suggested / default course structure or not at all. On the plus side: one could see one way this was all pulled together; on the downside: people may want to combine different modules in different lectures. E.g. if I create a lecture on renewables for my course, I will plug in also modules on how these are modelled in OSeMOSYS; someone else may not want to put OSeMOSYS in; someone else may want to put together an entire lecture ONLY on how things are done specifically in OSeMOSYS

**Comment by willu47** [comment]
Some ideas on how to do bits of there here

- https://github.com/github/learning-lab-components
- https://jekyllrb.com/docs/collections/

**Comment by lorenzo-sani** [comment]
Thanks @willu47, so far I managed to manually assign a presentation file with a tag and then list/group presentations depending on the tag. Now I´m trying to build a python script to access tags and change them depending on the input given by the user. However, I still need to find a way to read and change the YAML front matter of the files (which contains the tags).
