### ISSUE TITLE
Courses contain lectures

### ISSUE THREAD

**Issue by willu47** [KTH-dESA/teaching_kit#16]
### What?
A course contains one or more lectures.

### How?
We are limited by Jekyll in that we cannot nest collections - we cannot create a collection of collections. 

What we could do is create a new collection called `courses`, and then use a `courses` tag in the frontmatter of the lectures to assign those lectures to a course.

**Comment by lorenzo-sani** [comment]
It's not very clear to me what a ` course` would be:  one big presentation that contains all the lectures or one page that contains a link of the lectures contained in the course

**Comment by willu47** [comment]
Good question - I think a page, or section on a page that contains links to all the lectures
