### ISSUE TITLE
Pictures not showing anymore

### ISSUE THREAD

**Issue by lorenzo-sani** [KTH-dESA/teaching_kit#18]
I can´t manage to link pictures anymore and I get the following errors
lectures
`[2020-04-17 17:04:51] ERROR `/teaching_kit/lecture/2020/04/17/figures/ppt_demo/1_image.png' not found`

modules.
`[2020-04-17 17:08:30] ERROR `/teaching_kit/module/2020/01/01/figures/ppt_demo/1_image.png' not found.`

**Comment by lorenzo-sani** [comment]
I tried applying a permalink to get rid of the module/2020/01/01/`  but it's still not picking up pictures.
Permalink is a frontmatter variable that allows to set the address of one post

**Comment by willu47** [comment]
Looking at the Jekyll docs, its recommended to place images in the `assets/img` folder and then reference them using an absolute path e.g. `/assets/img/ppt_demo/image_1.png`

**Comment by willu47** [comment]
This might be an issue with remark as well. See this https://github.com/gnab/remark/wiki/Using-with-Jekyll#serving-from-a-project-folder

**Comment by lorenzo-sani** [comment]
great thanks, I could fix it using a mix of your solutions, now links to images look like this:
`<img src={{base.url}}/teaching_kit/assets/img/ppt_demo/1_image.png ... /> `
